# Generated by Django 3.2.12 on 2023-11-04 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('surname', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('age', models.IntegerField(default=0)),
                ('admin', models.BooleanField(default=False)),
                ('active_from', models.DateTimeField()),
            ],
        ),
    ]
