# Generated by Django 3.2.12 on 2023-11-21 21:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessGroup',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='AccessMembership',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('invite_data', models.DateTimeField(auto_now_add=True)),
                ('access_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.accessgroup')),
                ('inviter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_membership_invites', to='users.user')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user')),
            ],
        ),
        migrations.AddField(
            model_name='accessgroup',
            name='members',
            field=models.ManyToManyField(through='users.AccessMembership', to='users.User'),
        ),
    ]
